### ISSUE TITLE
[BUG]: yank highlight does not occur at the bottom half of larger files

### ISSUE THREAD

**Issue by chrisgrieser** [aleksey-rowan/obsidian-vim-yank-highlight#2]
Not 100% sure on the reproduction conditions, but as far as I can tell, the yank highlight fails when the file is large enough and you are (roughly) in the bottom half of the file. 

[example-file where that occurs](https://github.com/aleksey-rowan/obsidian-vim-yank-highlight/files/13718892/Lorem.Ipsum.md)

**Comment by aleksey-rowan** [comment]
Looks like the cursor offset is not calculated properly when the viewport is scrolled down. Should be (famous last words 😆) an easy fix.

Thank you for reporting!

**Comment by aleksey-rowan** [comment]
@chrisgrieser, this should be fixed in [#1.0.7](https://github.com/aleksey-rowan/obsidian-vim-yank-highlight/releases/tag/1.0.7). Could you please verify and close this issue if everything is hunky-dory?

**Comment by chrisgrieser** [comment]
yup, can confirm that everything works now. Thanks for the quick fix!
